name: ranger_gabo
description: "GabroDev"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flame: ^1.13.1
  flutter:
    sdk: flutter

  audioplayers: ^5.2.0
  cupertino_icons: ^1.0.6
  flame_audio: ^2.1.3
  go_router: ^13.0.1
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  nes_ui: ^0.12.1
  google_fonts: ^6.1.0
  logging: ^1.2.0

dev_dependencies:
  flame_test: ^1.14.0
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  test: ^1.24.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/city/
    - assets/images/objects/
    - assets/images/player/
    - assets/music/
    - assets/sfx/
    # - assets/images/scenery/

  fonts:
    - family: Press Start 2P
      fonts:
        - asset: assets/fonts/Press_Start_2P/PressStart2P-Regular.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"